# Don't print a new line at the start of the prompt
add_newline = false

format = """
[$hostname]("bold blue")\
$directory\
$git_branch\
$git_state\
$git_status\
$character
"""

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                         # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"  # The "success_symbol" is set to "âœ" with color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Hide the username. The username will only show in certain scenarios
[username]
disabled = false

[directory]
style = "bold italic #87A752"

# shows the hostname on new lines
[hostname]
ssh_only = false
disabled = false
style = "bold italic #87A752"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
